project:
  type: website

website:
  title: "Giant Morons ðŸ§ "
  site-url: https://zmackie.com
  description: "Deep learning and bad jokes."
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/zmackie
format:
  html:
    theme: 
      dark: yeti
    css: styles.css



